### ISSUE TITLE
Export contains invalid lines

### ISSUE THREAD

**Issue by Tomas2D** [ad-freiburg/osm2rdf#15]
Exported file https://osm2rdf.cs.uni-freiburg.de/ttl/cze.osm.ttl.bz2 (`2022-03-06`) 
does contain invalid lines, which results (during full import to Virtuoso) to the following errors. 

```
Message: TURTLE RDF loader, line 33407053: RDFGE: RDF box with a geometry RDF type and a non-geometry content
```

This is probably due to empty values inside `MULTIPOLYGON` function as can be seen in the following example.

```sparql
PREFIX osmrel: <https://www.openstreetmap.org/relation/> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#> 

INSERT DATA {
    GRAPH <http://example.com/osm/cze> {
        # This line is contained in TTL export
        osmrel:8291361 geo:hasGeometry "MULTIPOLYGON()"^^geo:wktLiteral . 
    }
}
```

Simple `cat + grep` expression shows that exported file contains 4 invalid rows, but maybe more will occur.
``` bash
$ cat cze.osm.ttl | grep 'MULTIPOLYGON()'
osmrel:8291361 geo:hasGeometry "MULTIPOLYGON()"^^geo:wktLiteral .
osmway:201387026 geo:hasGeometry "MULTIPOLYGON()"^^geo:wktLiteral .
osmway:203215812 geo:hasGeometry "MULTIPOLYGON()"^^geo:wktLiteral .
osmway:200235542 geo:hasGeometry "MULTIPOLYGON()"^^geo:wktLiteral .
```

**Comment by lehmann-4178656ch** [comment]
Thanks for bringing this to our attention. Direct links to the osm
objects for future reference:
* [osmrel:8291361](https://www.openstreetmap.org/relation/8291361)
* [osmway:201387026](https://www.openstreetmap.org/way/201387026)
* [osmway:203215812](https://www.openstreetmap.org/way/203215812)
* [osmway:200235542](https://www.openstreetmap.org/way/200235542)

Running a debug build on osmrel:8291361 with all required ways and nodes
triggers:
https://github.com/ad-freiburg/osm2rdf/blob/v0.2/src/osm/FactHandler.cpp#L232
```
Assertion `!boost::geometry::is_empty(geom)' failed.
```
The problem should be created in:
https://github.com/ad-freiburg/osm2rdf/blob/v0.2/src/osm/FactHandler.cpp#L227-L230

We want to replace/improve a related part in the future (inner/outer
geometry) and I hope we can use this here too.

I'll try to check if the original geometries are valid and if they are to keep them while still applying simplification.

**Comment by Tomas2D** [comment]
Thanks!
