### ISSUE TITLE
Outdated RDF dumps

### ISSUE THREAD

**Issue by Tomas2D** [ad-freiburg/osm2rdf#17]
On page https://osm2rdf.cs.uni-freiburg.de/ is being stated that RDF dumps are updated weekly, but HTTP headers shows that the last dump was made on **Thu, 06 Jan 2022 19:07:37 GMT**.

```
curl -I https://osm2rdf.cs.uni-freiburg.de/ttl/cze.osm.ttl.bz2
HTTP/1.1 200 OK
Date: Sat, 09 Apr 2022 20:20:10 GMT
Server: nginx/1.18.0 (Ubuntu)
Content-Type: application/octet-stream
Content-Length: 1986104540
Last-Modified: Thu, 06 Jan 2022 19:07:37 GMT
ETag: "61d73df9-76618cdc"
Expires: Sat, 09 Apr 2022 21:20:10 GMT
Cache-Control: max-age=3600
Accept-Ranges: bytes
```

Same applies to other countries.

Do you think that it will be possible to make a fresh dump or at least remove the statement about updates? I was quite confused at first sight when I uploaded the dump to the triple store and did not see any new data.

Thank you!

**Comment by hannahbast** [comment]
@Tomas2D Thanks for pointing this out + I am surprised that the dumps are not up to date. Let me find out what happened and come back to you very soon.

**Comment by hannahbast** [comment]
@Tomas2D Here is a quick update. Something started going wrong with our weekly cronjob on January 11. We usually get an email when one of our cronjob fails, but in this case it seems that the failing job did not write anything to stderr, so we did not receive an email. It's embarrassing. So thanks very much for pointing this out to us.

The process for updating the files is now running again. We will send another update here when it's done, hopefully soon.

**Comment by Tomas2D** [comment]
Perfect! Thank for blazingly fast response. I will definitely quote this project in my diploma thesis.

**Comment by hannahbast** [comment]
It's working again now! I just checked, and the latest files are from April 12. They should be updated again weekly from now on. Please let us know if there is again any problem.
