### ISSUE TITLE
Write RDF stats

### ISSUE THREAD

**Issue by lehmann-4178656ch** [ad-freiburg/osm2rdf#18]
Add stats for each RDF-File:
* Number of lines
  https://github.com/ad-freiburg/osm2rdf/blob/4903c44b761b017a340ca2775359d8b14423f812/src/ttl/Writer.cpp#L232
* Number of header
  https://github.com/ad-freiburg/osm2rdf/blob/4903c44b761b017a340ca2775359d8b14423f812/src/ttl/Writer.cpp#L155
* Number of triples = lines - header

E.g.
```
{
    "lines": 1337,
    "header": 42,
    "triples": 1295
}
```

This should be placed in a `.stats.json` file named like the normal output.

**Comment by patrickbr** [comment]
This is now used in the weekly updates for osm2rdf.cs.uni-freiburg.de, see https://github.com/ad-freiburg/osm-ttl-extracts/commit/90f3f0a6f1b9f2541c98aa732cece8d500960667
