### ISSUE TITLE
Docker image creation always runs benchmark 

### ISSUE THREAD

**Issue by LorenzBuehmann** [ad-freiburg/osm2rdf#23]
Hi,

created the Docker image from source, and so running benchmarks which from my point of view should be unnecessary. Looking at the `Dockerfile` I can see that just `make` is called and `make all` does indeed triggers the benchmark computation.

Not sure if this is intended, but it makes the image creation unnecessary slower then needed.

**Comment by hannahbast** [comment]
@LorenzBuehmann Thanks for pointing this out and I completely agree. I usually build without the `Dockerfile` (it's very easy to install the prerequisites on a machine, just execute the `apt-get ...` line from the `Dockerfile` with `sudo` on your machine) and then only compile the binary. This PR makes compilation of only `osm2rdf` the default, both with `docker` and when just doing `make`: https://github.com/ad-freiburg/osm2rdf/pull/25
