### ISSUE TITLE
cmake --install doesn't work

### ISSUE THREAD

**Issue by kiufta** [ad-freiburg/osm2rdf#32]
After building with `cmake --build . --target osm2rdf` I've wanted to properly install osm2rdf:
```
-- Install configuration: "Release"
CMake Error at benchmarks/vendor/google/benchmark/src/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "./osm2rdf/build/benchmarks/vendor/google/benchmark/src/libbenchmark.a":
  No such file or directory.
```

**Comment by lehmann-4178656ch** [comment]
Hello,

I try to talk to @patrickbr about whether or not we should create an INSTALL file to allow installation of osm2rdf. We mainly use  [docker](https://github.com/ad-freiburg/osm2rdf/blob/b62ff4fc7f90a496e55cc507b0e68d2ce1890921/Makefile#L83-L84) for deployment and use.

**Comment by patrickbr** [comment]
Personally I don't think we should require Docker for proper "installation". The classic `cmake --install` and/or `cmake .. && make install` should also work. I don't think this would be much work, it boils down to telling `cmake` where to copy the `osm2rdf` binary.

This is how `pfaedle` does it, for example: https://github.com/ad-freiburg/pfaedle/blob/master/CMakeLists.txt#L75

**Comment by patrickbr** [comment]
Thanks @lehmann-4178656ch for adding the `install` target
