### ISSUE TITLE
Remove all temporary files after osm2rdf has finished 

### ISSUE THREAD

**Issue by hannahbast** [ad-freiburg/osm2rdf#39]
Currently, the following three temporary files are left over after a successful build with `osm2rdf`.

```
spatial-areas_unnamed
spatial-nodes
spatial-ways
```

@lehmann-4178656ch @patrickbr  I suggest a PR to remove them, what do you think?

**Comment by patrickbr** [comment]
This is a good idea, I discussed this with @lehmann-4178656ch  a few weeks ago. @lehmann-4178656ch, as mentioned then, my usual approach is to open the output file and *immediately* unlink it. This way, the OS will make sure the file is gone as soon as the inode is no longer referenced (the files will also be gone if the program crashes or is aborted).

If you have time, it would be great if you could add this. (Also, we should add an option to disable the relation geometries dump, I think, but I can open a separate issue for that).

**Comment by patrickbr** [comment]
This is now fixed in master :)
