### ISSUE TITLE
Docker build errors on M2 chip mac

### ISSUE THREAD

**Issue by cansusam** [ad-freiburg/osm2rdf#55]
Following error pops up running `make docker-de` command on M2 mac with Ventura 13.5.
```
error: the clang compiler does not support '-march=native' [clang-diagnostic-error]
```

To fix, add `--platform linux/amd64 ` to `docker-build` command in `Makefile`:

```
docker-build:
	${DOCKER} build --platform linux/amd64 -t osm2rdf .
```

*`wget` should be added as a dependency to be able to build.

**Comment by patrickbr** [comment]
Clang 15 [seems to support](https://stackoverflow.com/a/72597669) `-march=native`, closing this issue for now.
