### ISSUE TITLE
Rename `ohm:start_date` and `ohm:end_date` to `osm:start_date` and `osm:end_date`?

### ISSUE THREAD

**Issue by patrickbr** [ad-freiburg/osm2rdf#77]
@lehmann-4178656ch, I just realized that the triples for the correctly typed end- and start dates include the dataset name (so they are `ohm:start_date` and `ohm:end_date`).

Shouldn't they be called `osm:start_date` and `osm:end_date` also for the OHM dataset for consistency? Their definition comes from the OSM wiki, and we keep the `osm` in the prefix for other things like `osmkey:`, `osm:way`, `osm:node`, `osmmeta`, etc.

**Comment by lehmann-4178656ch** [comment]
We've talked a bit about this and work started with #79 . Current consensus is that we mark all values we calculate/modify with the `osm2rdfkey:` prefix to signify that it may have changed its information.

**Comment by lehmann-4178656ch** [comment]
@patrickbr as #79 is merged, can we close this?

**Comment by patrickbr** [comment]
Closed, thank you, @lehmann-4178656ch
