### ISSUE TITLE
Incorrect timestamps for some elements in rdf turtle extracts on https://osm2rdf.cs.uni-freiburg.de

### ISSUE THREAD

**Issue by nicolano** [ad-freiburg/osm2rdf#94]
I have noticed that some OSM elements in the rdf turtle extracts on [https://osm2rdf.cs.uni-freiburg.de](https://osm2rdf.cs.uni-freiburg.de/#) have incorrect timestamps. For example, if I use this sparql query to get the node with the latest timestamp for a country like San Marino (but I have also tested this with other countries and every one shows this behaviour): 

```
PREFIX osmmeta: <https://www.openstreetmap.org/meta/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX osm: <https://www.openstreetmap.org/>
SELECT * WHERE {
  ?s rdf:type osm:node .
  ?s osmmeta:timestamp ?p .
} ORDER BY DESC(?p) LIMIT 1
```

The result will contain a node with a timestamp that is in the future: 

s = [4507026770](https://www.openstreetmap.org/node/4507026770)	p = 2024-11-17T20:42:00

However, when I convert the osm data for the country from geofabrik with osm2rdf on my local computer, everything is correct. So maybe this is not a problem with osm2rdf, but with the computer that created the extracts on [https://osm2rdf.cs.uni-freiburg.de](https://osm2rdf.cs.uni-freiburg.de/#)?

**Comment by lehmann-4178656ch** [comment]
We've done some reworking in the past few weeks and I've just run this query on the osm-planet instance https://qlever.cs.uni-freiburg.de/osm-planet/TcI9SP and the result:
```
?s	?p
1	360489619	2024-10-06T23:59:59
```

shows the same time as https://www.openstreetmap.org/node/360489619 could you please check this issue again?

**Comment by patrickbr** [comment]
This particular behavior was indeed fixed in https://github.com/ad-freiburg/osm2rdf/commit/541a305ed4a3d8bc94ec9288d1436cb613e49a54, so I am a bit surprised it popped up again last month. The weekly updates should be free of this issue since the end of May. I also just ran the same check as @lehmann-4178656ch on several additional instances, and the issue was not present.

**Comment by nicolano** [comment]
I can no longer reproduce the behaviour with the extracts on [osm2rdf](https://osm2rdf.cs.uni-freiburg.de)[https://osm2rdf.cs.uni-freiburg.de](https://osm2rdf.cs.uni-freiburg.de/#) either.

**Comment by lehmann-4178656ch** [comment]
Thank you for the confirmation.
